### ISSUE TITLE
Question, possible to combine this with 'gstreamer-tokio'

### ISSUE THREAD

**Issue by LrWm3** [gagbo/rust-prometheus-tokio#3]
https://github.com/standard-ai/tracing-gstreamer

Hello. I don't know rust or tokio very well, but I use gstreamer a lot. I was wondering if you thought it might be feasible to combine this project with the one I linked above.

My goal is to collect latency, data rate and buffers per second coming into and leaving each gstreamer element in a prometheus format.

I am merely curious if you think it is possible or if it would make sense at all. I will attempt it myself if you do.

Or if you would like to do so as a contractor I could look into hiring you for undertaking this work.

Please close upon reading.

Best regards!

**Comment by gagbo** [comment]
Hello,

I've seen you closed the issue, but just for the record:

This (prometheus-tokio) library is really meant to be included in binaries/end-products that happen to be asynchronous application with a tokio runtime, and not other libraries like what you seem to want to do.

The main reason for that is that because of [feature unification](https://doc.rust-lang.org/cargo/reference/features.html#feature-unification), including this library with non-default features will force everything in the dependency tree to use it too. I notably include the `tokio/rt` feature, which is probably present in _binaries_, but not in _libraries_.

Also, having the tokio metrics for an application makes more sense than having tokio metrics enabled by an extra library (like `tracing-gstreamer`)

I'm not open to contracting now, I have enough on my plate for the time being, thanks for the proposal though.

Regards,
Gerry
